sts:
  baseUri: https://security-token-service.nais.adeo.no

inntektskomponent:
  baseUri: https://app.adeo.no/inntektskomponenten-ws/rs

arena:
  baseUri: https://arena-ords.nais.adeo.no/arena/api

arenasoap:
  baseUri: https://arena.adeo.no/arena_ws/services
  oppgaveUri: https://arena.adeo.no/ail_ws/BehandleArbeidOgAktivitetOppgave_v1
  behandleSakOgAktivitetUri: https://arena.adeo.no/ail_ws/BehandleSakOgAktivitet_v1
  sts:
    url: https://sts.adeo.no/SecurityTokenServiceProvider/